name: CICD

on:
  push:
    branches: [deployment]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t shivam431/gift-orchids-ui .
      - name: Publish image to docker hub
        run: docker push shivam431/gift-orchids-ui:latest
        
  deploy:
    needs: build
    runs-on: [self-hosted, ip-172-31-3-77]
    steps:
      - name: Pull image from docker hub
        run: docker pull shivam431/gift-orchids-ui:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container shivam431/gift-orchids-ui